### PR TITLE
Re-introduce education stage step for ETAs

### PR DESCRIPTION
**Pull request by ethax-ross**
### Trello card

[Trello-4253](https://trello.com/c/8kSTY8rg/4253-review-teaching-subject-question-for-eta-candidates-in-adviser-funnel)

### Context

We removed the education stage step for ETAs but this led to a confusing subject you'd like to teach step where they had to select 'primary' as their subject if they wanted to teach at primary stage.

### Changes proposed in this pull request

- Re-introduce education stage step for ETAs

Re-introduce the education stage step for all candidates. Remove 'primary' from the subject you'd like to teach step as an option (as we only display this step to those interested in teaching secondary). Update the helper text for the subject you'd like to teach step.

### CODE REVIEW

**Review by EllieNodder — COMMENTED** [review]
Looks good to me!

**Comment by gemmadallmandfe** [comment]
@EllieNodder Whilst we are addressing this stage step, do you think we should improve the hint text
eg to say that you can change your mind later? and maybe that it helps us match them with an adviser?

(What we are saying is not strictly true - you get asked slightly different questions depending on  your answer so it does affect the sign-up process to that extent!)

image

**Comment by gemmadallmandfe** [comment]
Tested with Tejas to ensure that the requests were still being allocated to the right dashboards in CRM - all looks good

Once the hint text has been changed, I'm happy to approve/merge this

**Comment by gemmadallmandfe** [comment]
Candidate experience team are happy for this to be put into prod

I'll approve/merge on Monday so we can monitor

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me

**Pull request merged**
