### PR TITLE
Bug fixes and tidy up for the new TTA journey

### PR DESCRIPTION
**Pull request by ethax-ross**
Fixes a couple of edge case bugs in the new TTA journey, as well as making the steps more readable in general.

### CODE REVIEW

**Review by jebw — CHANGES_REQUESTED** [review]
Can this commit be its own PR - no need for it to be in the big refactor PR

**Review by jebw — CHANGES_REQUESTED** [review]
General purpose fix - can this be in its own PR

**Review by goodviber — CHANGES_REQUESTED** [review]
It looks really good, could we define the methods we are callling within skipped? elsewhere so we would only call then once within the skipped method?

**Comment by ethax-ross** [comment]
I agree we need to share the `skipped?` logic between steps so the complexity isn't compounding as you go further down the journey, but I don't think extracting it from the steps is the right approach here - instead I would put something in the wizard that lets a step query if a previous step was skipped. We could then have 2x QualificationRequired steps (one for maths/english and one for science) where the methods become:

```
def skipped?
  @wizard.skips?(RetakeGcseMathsEnglish)
end

...

def skipped?
  @wizard.skips?(RetakeGcsScience)
end
```

Either way I think this should be picked up as a separate PR once we have it working using the current pattern ^ there's a ticket for it in Jira.

**Review by goodviber — APPROVED** [review]

**Pull request merged**
