### PR TITLE
Updating 404 page text

### PR DESCRIPTION
**Pull request by EllieNodder**
### Trello card

https://trello.com/c/TU5jzJOx/4265-improve-adviser-service-404-page

### Context

Updating the 404 page content.

### CODE REVIEW

**Comment by gemmadallmandfe** [comment]
Looks good to me @EllieNodder !

**Comment by EllieNodder** [comment]
@gemmadallmandfe @ethax-ross is it me or is the spacing a bit weird?

image

**Comment by gemmadallmandfe** [comment]
@EllieNodder @ethax-ross It's pretty odd in prod already!

Can always put a separate ticket in the backlog for this?

image

**Review by ethax-ross — APPROVED** [review]

**Comment by ethax-ross** [comment]
Oh I just noticed the comments about spacing, I can take a look at that in this PR

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me

**Pull request merged**
