### PR TITLE
Add all path redirect to GiT

### PR DESCRIPTION
**Pull request by plisovin**
### Trello card

[Trello-4793](https://trello.com/c/pTz3BYQN/4793-coordinate-top-level-redirect-from-get-an-adviser-site-to-git-adviser-funnel)

### Context

Add wildcard redirect FROM `https://adviser-getintoteaching.education.gov.uk/` TO `https://getintoteaching.education.gov.uk/teacher-training-adviser/sign_up/identity` (once there are no people left in the middle of the funnel on the adviser site)

### CODE REVIEW

**Comment by gemmadallmandfe** [comment]
@plisovin I've tested this as best I could, by adding page slugs to the review app link - seems to work fine and redirects to the start of the funnel on GIT

**Review by gemmadallmandfe — DISMISSED** [review]
Looks good to me

**Review by asatwal — COMMENTED** [review]
@plisovin - Do you think route spec or a test for the redirect is a good idea here ? This is to safeguard against any regression.

**Comment by plisovin** [comment]
> @plisovin - Do you think route spec or a test for the redirect is a good idea here ? This is to safeguard against any regression.

Good point! Added a test in this [commit](ee0c60840451442481a6be9607b6a1820bb8288c)

**Review by gemmadallmandfe — APPROVED** [review]
Looks good to me (from the front end)

**Review by asatwal — APPROVED** [review]
👍 💯 LGTM

**Pull request merged**
